[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 4321
  port = 8888
  publish = "dist"
  framework = "astro"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 